import { Item } from '../modules/items/item.model.js';

const BUSINESS_ID = 'b2c3d4e5-f6a7-8901-bcde-f23456789012';

const DEMO_ITEMS = [
  {
    id: 'f6a7b8c9-d0e1-2345-f012-345678901234',
    businessId: BUSINESS_ID,
    name: 'Remera Lisa Algodón',
    price: 14999.99,
    stock: 0,
    visibleInCatalog: true,
    category: 'remera',
    gender: 'unisex',
    season: ['spring', 'summer', 'fall'],
    material: ['algodón 100%'],
    careInstructions: 'Lavar en frío, no usar blanqueador, planchar a temperatura media',
    brand: 'Básicos URB',
    description: 'Remera básica de algodón peinado, corte regular, cuello redondo reforzado. Ideal para uso diario o como base de outfits.',
  },
  {
    id: 'a7b8c9d0-e1f2-3456-0123-456789012345',
    businessId: BUSINESS_ID,
    name: 'Jean Slim Fit',
    price: 44999.99,
    stock: 0,
    visibleInCatalog: true,
    category: 'pantalon',
    gender: 'male',
    season: ['all'],
    material: ['denim 98%', 'elastano 2%'],
    careInstructions: 'Lavar del revés en frío, secar a la sombra, no planchar sobre bolsillos',
    brand: 'Denim Co.',
    description: 'Jean corte slim fit, tiro medio, cinco bolsillos. Tela con stretch para mayor comodidad y movimiento.',
  },
  {
    id: 'b8c9d0e1-f2a3-4567-1234-567890123456',
    businessId: BUSINESS_ID,
    name: 'Vestido Floral Midi',
    price: 54999.99,
    stock: 0,
    visibleInCatalog: true,
    category: 'vestido',
    gender: 'female',
    season: ['spring', 'summer'],
    material: ['viscosa 100%'],
    careInstructions: 'Lavar a mano en frío, no retorcer, planchar a temperatura baja',
    brand: 'Flor de Luna',
    description: 'Vestido midi con estampado floral, escote en V, mangas 3/4 con elástico en puños. Cintura elástica para mejor ajuste.',
  },
  {
    id: 'c9d0e1f2-a3b4-5678-2345-678901234567',
    businessId: BUSINESS_ID,
    name: 'Campera Rompevientos',
    price: 79999.99,
    stock: 0,
    visibleInCatalog: true,
    category: 'campera',
    gender: 'unisex',
    season: ['fall', 'winter'],
    material: ['nylon 100%', 'forro poliéster'],
    careInstructions: 'Lavar en ciclo suave, no usar suavizante, secar colgado',
    brand: 'Outdoor Pro',
    description: 'Campera ligera impermeable y transpirable, capucha ajustable guardable en cuello, bolsillos con cierre, puños elásticos.',
  },
  {
    id: 'd0e1f2a3-b4c5-6789-3456-789012345678',
    businessId: BUSINESS_ID,
    name: 'Zapatillas Urbanas',
    price: 89999.99,
    stock: 0,
    visibleInCatalog: true,
    category: 'calzado',
    gender: 'unisex',
    season: ['all'],
    material: ['cuero genuino', 'suela goma EVA'],
    careInstructions: 'Limpiar con paño húmedo, aplicar crema para cuero, no lavar en lavarropas',
    brand: 'Street Walk',
    description: 'Zapatillas urbanas de cuero, suela de goma EVA ligera, plantilla memory foam, cordones algodón encerado.',
  },
  {
    id: 'e1f2a3b4-c5d6-7890-4567-890123456789',
    businessId: BUSINESS_ID,
    name: 'Buzo Oversize',
    price: 39999.99,
    stock: 0,
    visibleInCatalog: true,
    category: 'buzo',
    gender: 'unisex',
    season: ['fall', 'winter'],
    material: ['algodón 80%', 'poliéster 20%', 'interior perchado'],
    careInstructions: 'Lavar en frío del revés, no usar secadora, planchar a temperatura media',
    brand: 'Comfy Wear',
    description: 'Buzo corte oversize, capucha con cordón, bolsillo canguro, puños y bajo con elástico. Interior perchado suave.',
  },
  {
    id: 'f2a3b4c5-d6e7-8901-5678-901234567890',
    businessId: BUSINESS_ID,
    name: 'Pollera Tableada',
    price: 29999.99,
    stock: 0,
    visibleInCatalog: true,
    category: 'pollera',
    gender: 'female',
    season: ['spring', 'summer'],
    material: ['algodón 95%', 'elastano 5%'],
    careInstructions: 'Lavar en frío, centrifugado suave, planchar a temperatura media',
    brand: 'Falda & Co',
    description: 'Pollera tableada corte A, cintura alta con elástico trasero, bolsillos laterales, largo midi. Tela con caída fluida.',
  },
  {
    id: 'a3b4c5d6-e7f8-9012-6789-012345678901',
    businessId: BUSINESS_ID,
    name: 'Camisa Oxford',
    price: 49999.99,
    stock: 0,
    visibleInCatalog: true,
    category: 'camisa',
    gender: 'male',
    season: ['all'],
    material: ['algodón oxford 100%'],
    careInstructions: 'Lavar en frío, planchar húmeda, colgar en percha',
    brand: 'Classic Fit',
    description: 'Camisa oxford corte regular, cuello botón abajo, puños redondeados, canesú trasero con pliegue. Tela texturada transpirable.',
  },
  {
    id: 'b4c5d6e7-f8a9-0123-7890-123456789012',
    businessId: BUSINESS_ID,
    name: 'Short Deportivo',
    price: 24999.99,
    stock: 0,
    visibleInCatalog: true,
    category: 'short',
    gender: 'unisex',
    season: ['summer'],
    material: ['políester 100%', 'malla interior'],
    careInstructions: 'Lavar en frío, secado rápido, no planchar',
    brand: 'Active Life',
    description: 'Short deportivo con malla interior, cintura elástica con cordón, bolsillos laterales con cierre, logo reflectivo.',
  },
  {
    id: 'c5d6e7f8-a9b0-1234-8901-234567890123',
    businessId: BUSINESS_ID,
    name: 'Musculosa Básica',
    price: 11999.99,
    stock: 0,
    visibleInCatalog: true,
    category: 'musculosa',
    gender: 'female',
    season: ['summer'],
    material: ['algodón 100%'],
    careInstructions: 'Lavar en frío, no usar blanqueador, secar a la sombra',
    brand: 'Básicos URB',
    description: 'Musculosa corte recto, tirantes anchos, escote redondo, largo cadera. Algodón peinado suave al tacto.',
  },
  {
    id: 'd6e7f8a9-b0c1-2345-9012-345678901234',
    businessId: BUSINESS_ID,
    name: 'Cinturón Cuero',
    price: 34999.99,
    stock: 0,
    visibleInCatalog: true,
    category: 'accesorio',
    gender: 'unisex',
    season: ['all'],
    material: ['cuero vacuno 100%', 'hebijón zamak'],
    careInstructions: 'Limpiar con paño seco, hidratar con crema para cuero, guardar enrollado',
    brand: 'Leather Craft',
    description: 'Cinturón de cuero vacuno curtido vegetal, ancho 3.5cm, hebilla cuadrada mate, 5 agujeros. Mejora con el uso.',
  },
  {
    id: 'e7f8a9b0-c1d2-3456-0123-456789012345',
    businessId: BUSINESS_ID,
    name: 'Mochila Impermeable',
    price: 59999.99,
    stock: 0,
    visibleInCatalog: true,
    category: 'accesorio',
    gender: 'unisex',
    season: ['all'],
    material: ['políester 600D', 'base lona encerada', 'cremalleras YKK'],
    careInstructions: 'Limpiar con cepillo suave y agua fría, no lavar en lavarropas, secar a la sombra',
    brand: 'Urban Pack',
    description: 'Mochila 25L impermeable, compartimento laptop 15", bolsillo frontal organizador, bolsillos laterales malla, espalda acolchada transpirable.',
  },
];

export async function seedItems() {
  for (const item of DEMO_ITEMS) {
    const existing = await Item.findOne({
      where: { businessId: item.businessId, name: item.name },
    });

    if (!existing) {
      await Item.create(item);
      console.log(`Item created: ${item.name}`);
    } else {
      console.log(`Item already exists: ${item.name}`);
    }
  }

  return DEMO_ITEMS;
}